global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rules and alerts
rule_files:
  # - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # API Gateway metrics
  - job_name: "api-gateway"
    static_configs:
      - targets: ["gateway:8080"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  # Mock services health monitoring
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:80"]
    metrics_path: "/health"
    scrape_interval: 30s

  - job_name: "product-service"
    static_configs:
      - targets: ["product-service:80"]
    metrics_path: "/health"
    scrape_interval: 30s

  # Redis monitoring
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s
