# =============================================================================
# ConfigMap for API Gateway Configuration
# =============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: api-gateway-system
data:
  # Gateway configuration
  gateway.yaml: |
    routes:
      - path: "/users"
        method: "GET"
        target_url: "http://user-service"
        auth_required: true

      - path: "/products"
        method: "GET"
        target_url: "http://product-service"
        auth_required: false

  # Application environment variables
  PORT: ":8080"
  JWT_EXPIRATION: "24h"
  RATE_LIMIT: "10"
  RATE_BURST_LIMIT: "20"
  RATE_CLEANUP: "1m"
  HEALTH_CHECK_INTERVAL: "10s"
  HEALTH_CHECK_TIMEOUT: "5s"
  READ_TIMEOUT: "30s"
  WRITE_TIMEOUT: "30s"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"

---
# ConfigMap for Prometheus configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: api-gateway
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: api-gateway-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'api-gateway'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - api-gateway
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: api-gateway
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - api-gateway
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
