apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: api-gateway-base

namespace: api-gateway

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - backend-services.yaml

images:
  - name: api-gateway
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/instance: api-gateway
      app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  config.kubernetes.io/origin: "k8s/base"

replicas:
  - name: api-gateway
    count: 2
  - name: product-service
    count: 2
  - name: user-service
    count: 1
