# =============================================================================
# Secret for API Gateway Sensitive Configuration
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: api-gateway-system
type: Opaque
data:
  # JWT Secret (base64 encoded)
  # Original: "production-jwt-secret-change-this-in-production"
  # To encode: echo -n "your-secret" | base64
  JWT_SECRET: cHJvZHVjdGlvbi1qd3Qtc2VjcmV0LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=

  # Database credentials (if needed in future)
  # DB_PASSWORD: cGFzc3dvcmQxMjM=

  # API Keys (if needed in future)
  # EXTERNAL_API_KEY: YWJjZGVmZ2hpams=
